const allGroupNames = [
  "doNotShowInTable",
  "yearBuilt",
  "income",
  "residentsAge",
  "residentsMaritalStatus",
  "householdType",
  "propertyOwnership",
  "buildingType",
  "immigrationBackground",
];

const allPropertyNames = [
  "neighbourhoodName",
  "municipalityName",
  "builtBefore2000",
  "builtAfter2000",
  "meanIncomePerResident",
  "meanIncomePerIncomeRecipient",
  "veryHighIncomeHouseholds",
  "lowIncomeHouseholds",
  "veryLowIncomeHouseholds",
  "belowSocialMinimumHouseholds",
  "residentsAge0to14Percentage",
  "residentsAge15to24Percentage",
  "residentsAge25to44Percentage",
  "residentsAge45to64Percentage",
  "residentsAge65AndOlder",
  "nonMarried",
  "married",
  "divorced",
  "widowed",
  "singlePersonHouseholds",
  "householdsWithChildren",
  "householdsWithoutChildren",
  "rentalProperties",
  "ownedProperties",
  "singleFamilyResidential",
  "multiFamilyResidential",
  "westernImmigrants",
  "nonWesternImmigrants",
  "residentsFromMorocco",
  "residentsFromAntillesOrAruba",
  "residentsFromSuriname",
  "residentsFromTurkey",
  "residentsOfOtherNonWesternBackground",
  "nonImmigrants",
];

module.exports = {
  allGroupNames,
  allPropertyNames,
};
